server {
    listen 8000;
    server_name localhost;

    location /daily-report/ {
        alias /usr/share/nginx/html/daily-report/;
        index index.html;
        try_files $uri $uri/ /daily-report/index.html;
    }

    location / {
        return 404;
    }
}
